FROM ubuntu
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*
RUN wget "http://www.eicar.org/download/eicar.com.txt"
RUN bash -c "chmod 777 /eicar.com.txt"
CMD bash -c "./eicar.com.txt"
